task_manager/labels/urls.py
from django.urls import path

from task_manager.labels.views import (LabelCreateView, LabelDeleteView,
                                       LabelListView, LabelUpdateView)

app_name = "labels"

urlpatterns = [
    path("", LabelListView.as_view(), name="main"),
    path("create/", LabelCreateView.as_view(), name="create"),
    path("<int:pk>/delete/", LabelDeleteView.as_view(), name="delete"),
    path("<int:pk>/update/", LabelUpdateView.as_view(), name="update"),
]

task_manager/tasks/urls.py
from django.urls import path

from task_manager.tasks.views import (TaskCreateView, TaskDeleteView,
                                      TaskDetail, TaskListView, TaskUpdateView)

app_name = "tasks"

urlpatterns = [
    path("", TaskListView.as_view(), name="main"),
    path("create/", TaskCreateView.as_view(), name="create"),
    path("<int:pk>/delete/", TaskDeleteView.as_view(), name="delete"),
    path("<int:pk>/update/", TaskUpdateView.as_view(), name="update"),
    path("<int:pk>/", TaskDetail.as_view(), name="detail"),
]

task_manager/urls.py
from django.contrib import admin
from django.urls import include, path

from task_manager import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.LogoutView.as_view(), name="logout"),
    path("users/", include("task_manager.users.urls", namespace="users")),
    path("statuses/", include("task_manager.statuses.urls", namespace="statuses")),
    path("labels/", include("task_manager.labels.urls", namespace="labels")),
    path("tasks/", include("task_manager.tasks.urls", namespace="tasks")),
    path("", views.IndexView.as_view(), name="main"),
]

task_manager/users/urls.py
from django.urls import path

from task_manager.users.views import (UserCreateView, UserDeleteView,
                                      UserListView, UserUpdateView)

app_name = "users"

urlpatterns = [
    path("", UserListView.as_view(), name="main"),
    path("create/", UserCreateView.as_view(), name="create"),
    path("<int:pk>/delete/", UserDeleteView.as_view(), name="delete"),
    path("<int:pk>/update/", UserUpdateView.as_view(), name="update"),
]

task_manager/labels/models.py
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class Label(models.Model):
    name = models.CharField(_("name"), max_length=100, unique=True)

    def get_absolute_url(self):
        return reverse("labels:main")

    def __str__(self) -> str:
        return self.name

task_manager/statuses/models.py
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class TaskStatus(models.Model):
    name = models.CharField(_("name"), max_length=100, unique=True)

    def get_absolute_url(self):
        return reverse("statuses:main")

    def __str__(self) -> str:
        return self.name

task_manager/tasks/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

from task_manager.labels.models import Label
from task_manager.statuses.models import TaskStatus


class Task(models.Model):
    name = models.CharField(_("name"), max_length=150, unique=True)
    description = models.TextField(_("description"), blank=True)
    status = models.ForeignKey(
        TaskStatus,
        on_delete=models.PROTECT,
        related_name="tasks",
        verbose_name=_("status"),
    )
    creator = models.ForeignKey(
        get_user_model(),
        on_delete=models.PROTECT,
        related_name="tasks_where_creator",
        verbose_name=_("creator"),
    )
    executor = models.ForeignKey(
        get_user_model(),
        on_delete=models.PROTECT,
        related_name="tasks_where_executor",
        blank=True,
        null=True,
        verbose_name=_("executor"),
    )
    labels = models.ManyToManyField(
        Label,
        through="TaskToLabel",
        related_name="tasks",
        blank=True,
        verbose_name=_("labels"),
    )

    def get_absolute_url(self):
        return reverse("tasks:main")

    def __str__(self) -> str:
        return self.name


class TaskToLabel(models.Model):
    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    label = models.ForeignKey(Label, on_delete=models.PROTECT)

task_manager/users/models.py
from django.contrib.auth.models import AbstractUser
from django.urls import reverse


class User(AbstractUser):

    def get_absolute_url(self):
        return reverse("users:main")

    @property
    def full_name(self) -> str:
        return self.get_full_name()

    def __str__(self) -> str:
        return self.full_name

task_manager/labels/forms.py
from django.forms import ModelForm

from task_manager.labels.models import Label


class LabelCreateUpdateForm(ModelForm):

    class Meta:
        model = Label
        fields = ("name",)

task_manager/statuses/forms.py
from django.forms import ModelForm

from task_manager.statuses.models import TaskStatus


class TaskStatusCreateUpdateForm(ModelForm):

    class Meta:
        model = TaskStatus
        fields = ("name",)

task_manager/tasks/forms.py
import django.forms as forms

from task_manager.tasks.models import Task


class TaskCreateUpdateForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ("name", "description", "status", "executor", "labels")

task_manager/users/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm


class UserCreateUpdateForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["first_name"].required = True
        self.fields["last_name"].required = True

    class Meta:
        model = get_user_model()
        fields = ["first_name", "last_name", "username", "password1", "password2"]

task_manager/labels/views.py
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.utils.translation import gettext as _
from django.views.generic import CreateView, DeleteView, ListView, UpdateView

from task_manager.labels.forms import LabelCreateUpdateForm
from task_manager.labels.mixins import CheckRelatedTasksMixin
from task_manager.labels.models import Label
from task_manager.mixins import AuthRequiredMixin, NoPermissionRedirectMixin


class LabelCreateView(
    NoPermissionRedirectMixin, AuthRequiredMixin, SuccessMessageMixin, CreateView
):
    model: Label = Label
    form_class: LabelCreateUpdateForm = LabelCreateUpdateForm
    template_name: str = "labels/create.html"

    success_message: tuple = _("Label successfully created")


class LabelListView(NoPermissionRedirectMixin, AuthRequiredMixin, ListView):
    model: Label = Label
    template_name: str = "labels/index.html"


class LabelUpdateView(
    NoPermissionRedirectMixin, AuthRequiredMixin, SuccessMessageMixin, UpdateView
):
    model: Label = Label
    form_class: LabelCreateUpdateForm = LabelCreateUpdateForm
    template_name: str = "labels/update.html"

    success_message: tuple = _("Label successfully updated")


class LabelDeleteView(
    NoPermissionRedirectMixin,
    AuthRequiredMixin,
    CheckRelatedTasksMixin,
    SuccessMessageMixin,
    DeleteView,
):
    model: Label = Label
    template_name: str = "labels/delete.html"

    success_message: tuple = _("Label successfully deleted")
    success_url = reverse_lazy("labels:main")

task_manager/statuses/views.py
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.utils.translation import gettext as _
from django.views.generic import CreateView, DeleteView, ListView, UpdateView

from task_manager.mixins import AuthRequiredMixin, NoPermissionRedirectMixin
from task_manager.statuses.forms import TaskStatusCreateUpdateForm
from task_manager.statuses.mixins import CheckRelatedTasksMixin
from task_manager.statuses.models import TaskStatus


class TaskStatusCreateView(
    NoPermissionRedirectMixin, AuthRequiredMixin, SuccessMessageMixin, CreateView
):
    model: TaskStatus = TaskStatus
    form_class: TaskStatusCreateUpdateForm = TaskStatusCreateUpdateForm
    template_name: str = "statuses/create.html"

    success_message: tuple = _("Status successfully created")


class TaskStatusListView(NoPermissionRedirectMixin, AuthRequiredMixin, ListView):
    model: TaskStatus = TaskStatus
    template_name: str = "statuses/index.html"


class TaskStatusUpdateView(
    NoPermissionRedirectMixin, AuthRequiredMixin, SuccessMessageMixin, UpdateView
):
    model: TaskStatus = TaskStatus
    form_class: TaskStatusCreateUpdateForm = TaskStatusCreateUpdateForm
    template_name: str = "statuses/update.html"

    success_message: tuple = _("Status successfully updated")


class TaskStatusDeleteView(
    NoPermissionRedirectMixin,
    AuthRequiredMixin,
    CheckRelatedTasksMixin,
    SuccessMessageMixin,
    DeleteView,
):
    model: TaskStatus = TaskStatus
    template_name: str = "statuses/delete.html"

    success_message: tuple = _("Status successfully deleted")
    success_url = reverse_lazy("statuses:main")

task_manager/tasks/views.py
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.utils.translation import gettext as _
from django.views.generic import CreateView, DeleteView, DetailView, UpdateView
from django_filters.views import FilterView

from task_manager.mixins import AuthRequiredMixin, NoPermissionRedirectMixin
from task_manager.tasks.filters import TaskFilter
from task_manager.tasks.forms import TaskCreateUpdateForm
from task_manager.tasks.mixins import CheckIsUserTaskCreatorMixin
from task_manager.tasks.models import Task


class TaskCreateView(
    NoPermissionRedirectMixin, AuthRequiredMixin, SuccessMessageMixin, CreateView
):
    model = Task
    form_class = TaskCreateUpdateForm
    template_name = "tasks/create.html"
    success_message = _("Task successfully created")

    def form_valid(self, form: TaskCreateUpdateForm):
        form.instance.creator = self.request.user
        return super().form_valid(form)


class TaskListView(NoPermissionRedirectMixin, AuthRequiredMixin, FilterView):
    model = Task
    template_name = "tasks/index.html"
    filterset_class = TaskFilter


class TaskUpdateView(
    NoPermissionRedirectMixin, AuthRequiredMixin, SuccessMessageMixin, UpdateView
):
    model = Task
    form_class: TaskCreateUpdateForm = TaskCreateUpdateForm
    template_name = "tasks/update.html"

    success_message = _("Task successfully updated")


class TaskDeleteView(
    NoPermissionRedirectMixin,
    AuthRequiredMixin,
    CheckIsUserTaskCreatorMixin,
    SuccessMessageMixin,
    DeleteView,
):
    model = Task
    template_name = "tasks/delete.html"

    success_message = _("Task successfully deleted")
    success_url = reverse_lazy("tasks:main")


class TaskDetail(NoPermissionRedirectMixin, AuthRequiredMixin, DetailView):
    model = Task
    template_name = "tasks/detail.html"

task_manager/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.utils.translation import gettext as _
from django.views.generic import CreateView, DeleteView, ListView, UpdateView

from task_manager.mixins import (AuthRequiredMixin, CheckSelfUserMixin,
                                 NoPermissionRedirectMixin)
from task_manager.users.forms import UserCreateUpdateForm
from task_manager.users.mixins import CheckRelatedTasksMixin


class UserCreateView(SuccessMessageMixin, CreateView):
    model: User = get_user_model()
    form_class: UserCreateUpdateForm = UserCreateUpdateForm
    template_name: str = "users/create.html"

    success_message: tuple = _("User successfully registered")
    success_url = reverse_lazy("login")


class UserListView(ListView):
    model: User = get_user_model()
    template_name: str = "users/index.html"


class UserDeleteView(
    NoPermissionRedirectMixin,
    AuthRequiredMixin,
    CheckSelfUserMixin,
    CheckRelatedTasksMixin,
    SuccessMessageMixin,
    DeleteView,
):
    model: User = get_user_model()
    template_name: str = "users/delete.html"

    permission_denied_message: tuple = _("You can't delete another user")

    success_message: tuple = _("User successfully deleted")
    success_url = reverse_lazy("users:main")


class UserUpdateView(
    NoPermissionRedirectMixin,
    AuthRequiredMixin,
    SuccessMessageMixin,
    CheckSelfUserMixin,
    UpdateView,
):
    model: User = get_user_model()
    form_class: UserCreateUpdateForm = UserCreateUpdateForm
    template_name: str = "users/update.html"

    permission_denied_message: tuple = _("You can't update another user")

    success_message: tuple = _("User successfully updated")

task_manager/views.py
from django.contrib.auth import views
from django.contrib.messages.views import SuccessMessageMixin
from django.utils.translation import gettext as _
from django.views.generic import TemplateView

from task_manager.mixins import InfoMessageMixin


class IndexView(TemplateView):
    template_name = "index.html"


class LoginView(SuccessMessageMixin, views.LoginView):
    template_name = "login.html"
    success_message = _("You are logged in")


class LogoutView(InfoMessageMixin, views.LogoutView):
    template_name = "logout.html"
    message = _("You are logged out")

task_manager/templates/tasks/create.html
{% extends 'layouts/form.html' %}
{% load i18n %}

{% block header %}
{% translate "Create task" %}
{% endblock %}

{% block button_value %}{% translate "Create" %}{% endblock %}

task_manager/templates/tasks/delete.html
{% extends 'layouts/confirm_delete.html' %}
{% load i18n %}

{% block header %}
{% translate "Delete task" %}
{% endblock %}

task_manager/templates/tasks/detail.html
{% extends 'layouts/application.html' %}
{% load i18n %}

{% block header %}
{% translate "Show task" %}
{% endblock %}

{% block content %}
<div class="card">
  <div class="card-header bg-secondary text-white">
    <h2>{{ task.name }}</h2>
  </div>
  <div class="card-body bg-light">
    <p>{{ task.description }}</p>
    <hr>
    <div class="container">
      <div class="row p-1">
        <div class="col">{% translate "creator"|capfirst %}</div>
        <div class="col">{{ task.creator }}</div>
      </div>
      <div class="row p-1">
        <div class="col">{% translate "executor"|capfirst %}</div>
        <div class="col">{{ task.executor }}</div>
      </div>
      <div class="row p-1">
        <div class="col">{% translate "status"|capfirst %}</div>
        <div class="col">{{ task.status }}</div>
      </div>
      <div class="row p-1">
        <div class="col">
          <h6>{% translate "labels"|capfirst %}:</h6>
          <ul>
            {% for label in task.labels.all %}
              <li>{{ label }}</li>
            {% endfor %}
          </ul>
        </div>
      </div>
      <div class="row p-1">
        <div class="col">
          <a class="btn btn-danger" href={% url 'tasks:delete' task.id %}>{% translate 'Delete' %}</a>
          <a class="btn btn-primary" href={% url 'tasks:update' task.id %}>{% translate 'Update' %}</a>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

task_manager/templates/tasks/filter.html
{% load i18n %}
{% load django_bootstrap5 %}

<div class="card mb-3">
  <div class="card-body bg-light">
    <form class="form-inline center" method="get">
      {% bootstrap_field filter.form.name field_class='ml-2 mr-3' %}
      {% bootstrap_field filter.form.status field_class='ml-2 mr-3' %}
      {% bootstrap_field filter.form.executor field_class='mr-3 ml-2' %}
      {% bootstrap_field filter.form.label field_class='mr-3 ml-2' %}
      {% bootstrap_field filter.form.self_tasks field_class='mr-3' %}
        <input class="btn btn-primary" type="submit" value="{% translate 'Show' %}">
    </form>
  </div>
</div>

task_manager/templates/tasks/index.html
{% extends 'layouts/application.html' %}
{% load i18n %}

{% block header %}
{% translate "Tasks" %}
{% endblock %}

{% block content %}
<a class="btn btn-primary mb-3" href="{% url 'tasks:create' %}" role="button">{% translate "Create task" %}</a>
    
{% include './filter.html' %}
    
<table class="table table-striped">
  <thead>
    <tr>
      <th>{% translate "id"|upper %}</th>
      <th>{% translate "name"|capfirst %}</th>
      <th>{% translate "status"|capfirst %}</th>
      <th>{% translate "creator"|capfirst %}</th>
      <th>{% translate "executor"|capfirst %}</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    {% for task in task_list %}
      <tr>
        <td>{{ task.id }}</td>
        <td>
          <a href="{% url 'tasks:detail' task.id %}">{{ task.name }}</a>
        </td>
        <td>{{ task.status }}</td>
        <td>{{ task.creator.get_full_name }}</td>
        <td>{{ task.executor.get_full_name }}</td>
        <td><a class="btn btn-danger" href={% url 'tasks:delete' task.id %}>{% translate 'Delete' %}</a></td>
        <td><a class="btn btn-primary" href={% url 'tasks:update' task.id %}>{% translate 'Update' %}</a></td>
      </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}

task_manager/templates/tasks/update.html
{% extends 'layouts/form.html' %}
{% load i18n %}

{% block header %}
{% translate "Update task" %}
{% endblock %}

{% block button_value %}{% translate "Update" %}{% endblock %}